import { HttpClient, HttpErrorResponse, HttpParams } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { MessageService } from 'primeng/api';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputNumberModule } from 'primeng/inputnumber';
import { InputTextModule } from 'primeng/inputtext';
import { SelectModule } from 'primeng/select';
import { TableModule } from 'primeng/table';
import { TagModule } from 'primeng/tag';
import { TextareaModule } from 'primeng/textarea';
import { AuthService } from '../core/auth.service';
import { CommercialCatalogProduct, InventoryMovement, InventoryReservation, Paginated, Stock } from '../core/models';

type InventoryView = 'stocks' | 'movements' | 'reservations';

@Component({
  selector: 'app-inventory',
  standalone: true,
  imports: [ReactiveFormsModule, FormsModule, ButtonModule, DialogModule, InputNumberModule, InputTextModule, SelectModule, TableModule, TagModule, TextareaModule],
  template: `
    <div class="page-toolbar"><div><span class="eyebrow">Inventario inicial</span><h2>Existencias y reservas</h2><p>El disponible se calcula como físico menos reservado; confirmar no descuenta el saldo físico.</p></div>@if (auth.can('inventory.movements.create')) { <p-button label="Registrar movimiento" icon="pi pi-plus" (onClick)="openMovement()" /> }</div>
    <div class="subnav"><button type="button" [class.active]="view()==='stocks'" (click)="view.set('stocks')"><i class="pi pi-warehouse"></i> Existencias</button><button type="button" [class.active]="view()==='movements'" (click)="view.set('movements')"><i class="pi pi-arrow-right-arrow-left"></i> Movimientos</button><button type="button" [class.active]="view()==='reservations'" (click)="view.set('reservations')"><i class="pi pi-lock"></i> Reservas</button></div>
    @if (view()==='stocks') {
      <div class="filter"><input pInputText [ngModel]="search()" (ngModelChange)="search.set($event)" (keyup.enter)="loadStocks()" placeholder="Producto, código o presentación" /><p-button label="Buscar" icon="pi pi-search" [outlined]="true" (onClick)="loadStocks()" /></div>
      <div class="stock-grid">@for (stock of stocks(); track stock.id) { <article><header><span class="stock-icon"><i class="pi pi-box"></i></span><p-tag [severity]="Number(stock.availableQuantity)>0?'success':'warn'" [value]="Number(stock.availableQuantity)>0?'Disponible':'Sin disponible'" /></header><h3>{{ stock.presentation.product?.name }}</h3><p>{{ stock.presentation.description }} · {{ stock.presentation.unit.abbreviation }}</p><dl><div><dt>Físico</dt><dd>{{ stock.physicalQuantity }}</dd></div><div><dt>Reservado</dt><dd>{{ stock.reservedQuantity }}</dd></div><div class="available"><dt>Disponible</dt><dd>{{ stock.availableQuantity }}</dd></div></dl><small>Versión {{ stock.version }}</small></article> } @empty { <div class="empty"><i class="pi pi-warehouse"></i><strong>No existen saldos registrados</strong><span>Registra un ingreso para crear la existencia inicial.</span></div> }</div>
    }
    @if (view()==='movements') { <div class="table-card"><p-table [value]="movements()" [loading]="loading()" [scrollable]="true"><ng-template #header><tr><th>Fecha</th><th>Presentación</th><th>Tipo</th><th>Cantidad</th><th>Saldo</th><th>Motivo</th><th>Usuario</th></tr></ng-template><ng-template #body let-movement><tr><td>{{ formatDate(movement.occurredAt) }}</td><td><div class="stack"><strong>{{ movement.stock.presentation.product?.name }}</strong><small>{{ movement.stock.presentation.description }}</small></div></td><td><p-tag severity="info" [value]="movement.type" /></td><td>{{ movement.quantity }}</td><td>{{ movement.previousBalance }} → {{ movement.newBalance }}</td><td>{{ movement.reason }}</td><td>{{ movement.user.name }}</td></tr></ng-template></p-table></div> }
    @if (view()==='reservations') { <div class="table-card"><p-table [value]="reservations()" [loading]="loading()" [scrollable]="true"><ng-template #header><tr><th>Fecha</th><th>Pedido</th><th>Cliente</th><th>Presentación</th><th>Reservado</th><th>Pendiente</th><th>Estado</th></tr></ng-template><ng-template #body let-reservation><tr><td>{{ formatDate(reservation.createdAt) }}</td><td><strong>{{ reservation.orderDetail.order?.code }}</strong></td><td>{{ reservation.orderDetail.order?.customer?.businessName }}</td><td><div class="stack"><strong>{{ reservation.stock.presentation.product?.name }}</strong><small>{{ reservation.stock.presentation.description }}</small></div></td><td>{{ reservation.quantity }}</td><td>{{ reservation.orderDetail.pendingQuantity }}</td><td><p-tag severity="success" [value]="reservation.status" /></td></tr></ng-template></p-table></div> }

    <p-dialog [visible]="movementDialog()" (visibleChange)="movementDialog.set($event)" [modal]="true" [style]="{width:'min(640px,96vw)'}" header="Registrar movimiento de inventario" [draggable]="false"><form [formGroup]="movementForm" (ngSubmit)="saveMovement()"><div class="form-grid"><label class="full"><span>Presentación *</span><p-select formControlName="presentationId" [options]="presentationOptions()" optionLabel="label" optionValue="value" [filter]="true" /></label><label><span>Tipo *</span><p-select formControlName="type" [options]="movementTypes" /></label><label><span>Cantidad *</span><p-inputnumber formControlName="quantity" [min]="0.001" [maxFractionDigits]="3" /></label><label class="full"><span>Motivo *</span><textarea pTextarea formControlName="reason" rows="3"></textarea></label></div><p class="help">Los movimientos no se eliminan. Una corrección debe registrarse mediante un nuevo ajuste trazable.</p><div class="dialog-footer"><p-button type="button" label="Cancelar" severity="secondary" [text]="true" (onClick)="movementDialog.set(false)" /><p-button type="submit" label="Registrar movimiento" icon="pi pi-check" [loading]="saving()" /></div></form></p-dialog>
  `,
  styles: [`
    .page-toolbar{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;margin-bottom:1rem}.page-toolbar h2{margin:.35rem 0;font-size:clamp(1.8rem,3vw,2.7rem);letter-spacing:-.05em}.page-toolbar p,.help{margin:0;color:var(--text-muted);font-size:.75rem}.eyebrow{color:var(--accent);font-size:.68rem;font-weight:850;letter-spacing:.14em;text-transform:uppercase}.subnav{display:flex;gap:.4rem;margin-bottom:1rem;padding:.3rem;border:1px solid var(--surface-border);border-radius:.8rem;background:#fff}.subnav button{display:flex;align-items:center;gap:.45rem;padding:.65rem .8rem;border:0;border-radius:.55rem;color:var(--text-muted);background:transparent;cursor:pointer}.subnav button.active{color:#fff;background:var(--brand-700)}.filter{display:grid;grid-template-columns:minmax(16rem,.6fr) auto;justify-content:start;gap:.65rem;margin-bottom:1rem}.stock-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.stock-grid article{padding:1.25rem;border:1px solid var(--surface-border);border-radius:1rem;background:#fff}.stock-grid header{display:flex;justify-content:space-between}.stock-icon{width:2.8rem;height:2.8rem;display:grid;place-items:center;border-radius:.8rem;color:var(--brand-700);background:#dff1fb}.stock-grid h3{margin:1rem 0 .25rem}.stock-grid article>p{margin:0;color:var(--text-muted);font-size:.7rem}.stock-grid dl{display:grid;grid-template-columns:repeat(3,1fr);gap:.45rem;margin:1rem 0}.stock-grid dl div{padding:.65rem;border-radius:.65rem;background:#f6f9fb}.stock-grid dt{color:var(--text-muted);font-size:.58rem}.stock-grid dd{margin:.2rem 0 0;font-size:.9rem;font-weight:800}.stock-grid .available{color:#075e6b;background:#e1f6f7}.stock-grid article>small{color:var(--text-muted);font-size:.6rem}.table-card{overflow:hidden;border:1px solid var(--surface-border);border-radius:1rem;background:#fff}.stack strong,.stack small{display:block}.stack small{color:var(--text-muted);font-size:.63rem;margin-top:.2rem}.empty{grid-column:1/-1;min-height:13rem;display:grid;place-items:center;align-content:center;gap:.5rem;color:var(--text-muted)}.empty i{font-size:2rem}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;padding-top:.5rem}.form-grid label{display:grid;gap:.4rem}.form-grid label>span{color:#344b61;font-size:.7rem;font-weight:750}.form-grid .full{grid-column:1/-1}.form-grid textarea{width:100%}.help{margin-top:1rem}.dialog-footer{display:flex;justify-content:flex-end;gap:.5rem;margin-top:1.5rem;padding-top:1rem;border-top:1px solid var(--surface-border)}@media(max-width:950px){.stock-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.page-toolbar{align-items:flex-start;flex-direction:column}.stock-grid,.filter,.form-grid{grid-template-columns:1fr}.form-grid .full{grid-column:auto}}
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InventoryComponent implements OnInit {
  private readonly http=inject(HttpClient);private readonly fb=inject(FormBuilder);private readonly messages=inject(MessageService);protected readonly auth=inject(AuthService);
  protected readonly view=signal<InventoryView>('stocks');protected readonly loading=signal(false);protected readonly saving=signal(false);protected readonly search=signal('');
  protected readonly stocks=signal<Stock[]>([]);protected readonly movements=signal<InventoryMovement[]>([]);protected readonly reservations=signal<InventoryReservation[]>([]);protected readonly products=signal<CommercialCatalogProduct[]>([]);protected readonly movementDialog=signal(false);
  protected readonly movementTypes=[{label:'Ingreso',value:'INGRESO'},{label:'Ajuste positivo',value:'AJUSTE_POSITIVO'},{label:'Ajuste negativo',value:'AJUSTE_NEGATIVO'}];
  protected readonly movementForm=this.fb.nonNullable.group({presentationId:['',Validators.required],type:['INGRESO',Validators.required],quantity:[1,[Validators.required,Validators.min(.001)]],reason:['',[Validators.required,Validators.minLength(2)]]});
  protected readonly Number=Number;
  ngOnInit():void{this.loadStocks();this.loadMovements();this.loadReservations();this.http.get<Paginated<CommercialCatalogProduct>>('/api/catalogo',{params:new HttpParams().set('limit',100)}).subscribe({next:r=>this.products.set(r.data)});}
  protected presentationOptions=()=>this.products().flatMap(p=>p.presentations.map(x=>({label:`${p.name} · ${x.description}`,value:x.id})));
  protected loadStocks():void{this.loading.set(true);let params=new HttpParams().set('limit',100);if(this.search().trim())params=params.set('q',this.search().trim());this.http.get<Paginated<Stock>>('/api/inventario/existencias',{params}).subscribe({next:r=>{this.stocks.set(r.data);this.loading.set(false)},error:e=>this.fail(e)});}
  private loadMovements():void{this.http.get<Paginated<InventoryMovement>>('/api/inventario/movimientos',{params:new HttpParams().set('limit',100)}).subscribe({next:r=>this.movements.set(r.data),error:e=>this.fail(e)});}
  private loadReservations():void{this.http.get<Paginated<InventoryReservation>>('/api/inventario/reservas',{params:new HttpParams().set('limit',100)}).subscribe({next:r=>this.reservations.set(r.data),error:e=>this.fail(e)});}
  protected openMovement():void{this.movementForm.reset({presentationId:this.presentationOptions()[0]?.value??'',type:'INGRESO',quantity:1,reason:''});this.movementDialog.set(true);}
  protected saveMovement():void{if(this.movementForm.invalid)return this.movementForm.markAllAsTouched();this.saving.set(true);this.http.post('/api/inventario/movimientos',this.movementForm.getRawValue()).subscribe({next:()=>{this.saving.set(false);this.movementDialog.set(false);this.messages.add({severity:'success',summary:'Movimiento registrado',detail:'El saldo físico fue actualizado y auditado.'});this.loadStocks();this.loadMovements();},error:e=>this.failSave(e)});}
  protected formatDate(value:string):string{return new Intl.DateTimeFormat('es-BO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
  private fail(error:unknown):void{this.loading.set(false);this.messages.add({severity:'error',summary:'No se pudo cargar',detail:this.error(error)});}private failSave(error:unknown):void{this.saving.set(false);this.messages.add({severity:'error',summary:'No se pudo registrar',detail:this.error(error)});}private error(error:unknown):string{if(!(error instanceof HttpErrorResponse))return'Error inesperado';const message=error.error?.message;return Array.isArray(message)?message.join('. '):message||'La solicitud no pudo completarse';}
}
