export enum PreparationStatus {
  PENDING = 'PENDIENTE',
  IN_PROGRESS = 'EN_PREPARACION',
  OBSERVED = 'OBSERVADA',
  PREPARED = 'PREPARADA',
  ASSIGNED = 'ASIGNADA',
  DISPATCHED = 'DESPACHADA',
}

export enum PreparationEvent {
  START = 'INICIO',
  PROGRESS = 'AVANCE',
  OBSERVATION = 'OBSERVACION',
  CONFIRMATION = 'CONFIRMACION',
  ASSIGNMENT = 'ASIGNACION',
  DISPATCH = 'DESPACHO',
}
