export enum TrackingLinkStatus {
  ACTIVE = 'ACTIVO',
  EXPIRED = 'EXPIRADO',
  REVOKED = 'REVOCADO',
}

export enum PublicTrackingStatus {
  ORDER_CONFIRMED = 'PEDIDO_CONFIRMADO',
  IN_PREPARATION = 'EN_PREPARACION',
  PREPARED = 'PREPARADO',
  IN_ROUTE = 'EN_RUTA',
  DELIVERED = 'ENTREGADO',
  DELIVERY_NOT_COMPLETED = 'ENTREGA_NO_COMPLETADA',
}

export enum NotificationEvent {
  ORDER_CONFIRMED = 'PEDIDO_CONFIRMADO',
  RELEVANT_CHANGE = 'CAMBIO_RELEVANTE',
  ROUTE_DEPARTURE = 'SALIDA_RUTA',
  NEXT_DELIVERY = 'PROXIMA_ENTREGA',
  DELIVERED = 'ENTREGADO',
  DELIVERY_NOT_COMPLETED = 'ENTREGA_NO_COMPLETADA',
  PAYMENT_RECEIVED = 'PAGO_RECIBIDO',
}

export enum NotificationStatus {
  PENDING = 'PENDIENTE',
  PROCESSING = 'PROCESANDO',
  SENT = 'ENVIADO',
  DELIVERED = 'ENTREGADO',
  RETRY = 'REINTENTO',
  FAILED = 'FALLIDO',
}

export enum NotificationAttemptStatus {
  SENT = 'ENVIADO',
  RECOVERABLE_FAILURE = 'FALLIDO_RECUPERABLE',
  DEFINITIVE_FAILURE = 'FALLIDO_DEFINITIVO',
}

